config/routes.rb
SurveysApp::Application.routes.draw do

  namespace :backoffice do
    resources :surveys, except: [:show] do 
      resources :questions, only: [:new, :create, :edit, :update, :destroy]
    end
    resources :attempts, :only => [:new, :create]
  end

  resources :surveys, only: [:index] do 
    resources :attempts, :only => [:new, :create] do 
      member {get 'results'}
    end
  end

  resources :attempts, only: [:index] do 
    member { get 'results' }
  end

  devise_for :users
  get "home/index"

  root 'surveys#index'

end

app/controllers/backoffice/attempts_controller.rb
class Backoffice::AttemptsController < ApplicationController

  helper 'backoffice/surveys'

  before_filter :load_active_survey
  before_filter :normalize_attempts_data, :only => :create

  def new
    @participant = current_user # you have to decide what to do here

    unless @survey.nil?
      @attempt = @survey.attempts.new
      @attempt.answers.build
    end
  end

  def create
    @attempt = @survey.attempts.new(attempt_params)
    @attempt.participant = current_user

    if @attempt.valid? && @attempt.save
      redirect_to view_context.new_attempt, alert: I18n.t("attempts_controller.#{action_name}")
    else
      render :action => :new
    end
  end

  private

  def load_active_survey
    @survey =  Survey::Survey.active.first
  end

  def normalize_attempts_data
    normalize_data!(params[:survey_attempt][:answers_attributes])
  end

  def normalize_data!(hash)
    multiple_answers = []
    last_key = hash.keys.last.to_i

    hash.keys.each do |k|
      if hash[k]['option_id'].is_a?(Array)
        if hash[k]['option_id'].size == 1
          hash[k]['option_id'] = hash[k]['option_id'][0]
          next
        else
          multiple_answers <<  k if hash[k]['option_id'].size > 1
        end
      end
    end

    multiple_answers.each do |k|
      hash[k]['option_id'][1..-1].each do |o|
        last_key += 1
        hash[last_key.to_s] = hash[k].merge('option_id' => o)
      end
      hash[k]['option_id'] = hash[k]['option_id'].first
    end
  end

  def attempt_params
    rails4? ? params_whitelist : params[:survey_attempt]
  end

  def params_whitelist
    params.require(:survey_attempt).permit(Survey::Attempt::AccessibleAttributes)
  end
end

app/controllers/backoffice/questions_controller.rb
class Backoffice::QuestionsController < ApplicationController
  before_action :authenticate_user!

  before_filter :load_survey

  def new
    @question = Survey::Question.new
    @question.survey_id = @survey.id
  end

  def create
    @question = Survey::Question.new(question_params)
    if(@question.save)
      redirect_to edit_backoffice_survey_path(@survey)
    else
      render :new
    end
  end

  def edit
    @question = Survey::Question.find(params[:id])
  end

  def update
    @question = Survey::Question.find(params[:id])
    if(@question.update_attributes(question_params))
      redirect_to edit_backoffice_survey_question_path(@survey, @question)
    else
      render :edit
    end
  end

  def destroy
    @question = Survey::Question.find(params[:id])
    @question.destroy
    redirect_to edit_backoffice_survey_path(@survey)
  end

  private 

  def load_survey
    @survey = Survey::Survey.find(params[:survey_id])
  end

  #Survey::Question::AccessibleAttributes does not work because it has survey instead of survey_id
  def question_params
    params.require(:survey_question).permit(question_whitelist)
  end

  def question_whitelist
    [:text, :survey_id, {:options_attributes=>[:text, :correct, :weight, :id, :_destroy]}, :id, :_destroy]  
  end

end

app/controllers/backoffice/surveys_controller.rb
class Backoffice::SurveysController < ApplicationController
  before_action :authenticate_user!

  before_filter :load_survey, :only => [:show, :edit, :update]

  def index
    @surveys = Survey::Survey.all
  end

  def new
    @survey = Survey::Survey.new
  end

  def create
    @survey = Survey::Survey.new(survey_params)
    if @survey.valid? && @survey.save
      default_redirect
    else
      render :action => :new
    end
  end

  def edit
  end

  def show
  end

  def update
    if @survey.update_attributes(survey_params)
      default_redirect
    else
      render :action => :edit
    end
  end

  private

  def default_redirect
    redirect_to edit_backoffice_survey_path(@survey), alert: I18n.t("surveys_controller.#{action_name}")
  end

  def load_survey
    @survey = Survey::Survey.find(params[:id])
  end

  def survey_params
    rails4? ? params_whitelist : params[:survey_survey]
  end

  def params_whitelist
    params.require(:survey_survey).permit(Survey::Survey::AccessibleAttributes)
  end

end

app/controllers/surveys_controller.rb
class SurveysController < ApplicationController
  before_action :authenticate_user!
  
  def index
    @surveys = Survey::Survey.all
  end
  
end

app/helpers/backoffice/questions_helper.rb
module Backoffice::QuestionsHelper

  def link_to_add_field(name, f, association)
    new_object = f.object.class.reflect_on_association(association).klass.new
    fields = f.fields_for(association, new_object,:child_index => "new_#{association}") do |builder|
      render(association.to_s.singularize + "_fields", :f => builder)
    end
    link_to_function(name, "addField(this, \"#{association}\", \"#{escape_javascript(fields)}\")",
    :id=>"add-attach",
    :class=>"btn btn-small btn-info")
  end

  def link_to_remove_field(name, f, html_opts = {})
    html_opts[:id] = 'remove-attach' unless html_opts[:id]
    f.hidden_field(:_destroy) +
    link_to_function(raw(name), "removeField(this)", html_opts)
  end

  def question_scope(parent, resource)
    if action_name =~ /new|create/
      backoffice_survey_questions_path(parent, resource)
    elsif action_name =~ /edit|update/
      backoffice_survey_question_path(parent, resource)
    end
  end
end

app/helpers/backoffice/surveys_helper.rb
module Backoffice::SurveysHelper
  def link_to_remove_field(name, f)
    f.hidden_field(:_destroy) +
    link_to_function(raw(name), "removeField(this)", :id =>"remove-attach")
  end

  def new_survey
    new_survey_path
  end

  def edit_survey(resource)
    edit_survey_path(resource)
  end

  def survey_scope(resource)
    if action_name =~ /new|create/
      backoffice_surveys_path(resource)
    elsif action_name =~ /edit|update/
      backoffice_survey_path(resource)
    end
  end

  def new_attempt
    new_attempt_path
  end

  def attempt_scope(resource)
    if action_name =~ /new|create/
     attempts_path(resource)
    elsif action_name =~ /edit|update/
      attempt_path(resource)
    end
  end

  def link_to_add_field(name, f, association)
    new_object = f.object.class.reflect_on_association(association).klass.new
    fields = f.fields_for(association, new_object,:child_index => "new_#{association}") do |builder|
      render(association.to_s.singularize + "_fields", :f => builder)
    end
    link_to_function(name, "addField(this, \"#{association}\", \"#{escape_javascript(fields)}\")",
    :id=>"add-attach",
    :class=>"btn btn-small btn-info")
  end

  def survey_status(survey)
    survey.active ? 'active' : 'Disabled'
  end
end

app/views/backoffice/surveys/_form.html.erb
<%= form_for(@survey, :url => survey_scope(@survey)) do |f| %>

  <% if f.object.errors.messages.any? %>
    <ul>
      <% f.object.errors.messages.each_pair do |field, msg| %>
        <li>
          <%= "#{field} - #{msg}" %>
        </li>
      <% end -%>
    </ul>
  <% end -%>
  <div class="row">
    <div class="col-lg-5">
      <div class="form-group">
        <label for="">Name</label>
        <%= f.text_field :name, class: 'form-control' %>
      </div>
      <div class="form-group">
        <label for="">Attempts Number</label>
        <%= f.text_field :attempts_number, class: 'form-control' %>
      </div>
      <div class="form-group">
        <label for="">Active</label>
        <%= f.select  :active, ['true', 'false'], {}, class: 'form-control' %>
      </div>
      <div class="form-group">
        <label for="">Description</label>
        <%= f.text_area  :description,  size: '100x5', class: 'form-control' %>
      </div>
      <div class="form-group">
        <%= f.submit class: 'btn btn-primary' %>
      </div>
    </div>
    <% if @survey.persisted? %>
    <div class="col-lg-6 col-lg-offset-1">
      <h3>Questions</h3>
      <ul class="list-unstyled">
        <% @survey.questions.each do |question| %>
          <li class="top-padding-buffer">
            <div class="col-lg-6">
              <%= link_to question.text, edit_backoffice_survey_question_path(@survey,question) %>
            </div>
            <div class="col-lg-6">
              <%= link_to backoffice_survey_question_path(@survey, question), method: :delete , class: 'btn btn-danger' do %>
                <span class='glyphicon glyphicon-remove'></span>
              <% end %>
            </div>
            <div class="clearfix"></div>
          </li>
        <% end %>
      </ul>
      <%= link_to 'Add a Question', new_backoffice_survey_question_path(survey_id: @survey.id), class: 'btn btn-primary' %>
    </div>
    <% end %>
    <!--
    <div class="col-lg-5 col-lg-offset-1">
      <h3>Questions</h3>
      <div class="field">
        <ul class="list-unstyled">
          <%= f.fields_for :questions do |builder| %>
            <%= render "question_fields", :f => builder %>
          <% end %>
        </ul>
        <%= link_to_add_field "Add a new Question", f, :questions %>
      </div>
    </div>-->
  </div>
<% end -%>

<script type="text/javascript">
  // remove attachment field
  function removeField(link) {
    $(link).prev("input[type=hidden]").val("true");
    tag = $(link).closest("li")
    tag.hide("fade in").addClass("deleted");
  }

  // add attachment field
  function addField(link, association, content) {
    var new_id = new Date().getTime();
    var regexp = new RegExp("new_" + association, "g");
    var html = $(content.replace(regexp, new_id)).hide();
    html.appendTo($(link).closest("div.field").find("ul").first()).slideDown("slow");
  }
</script>

app/views/backoffice/surveys/_option_fields.html.erb
<li>
  <div class="field">
    <%= f.label :text %> <br/ >
    <%= f.text_field :text %>
    <%= f.check_box :correct %>
    <%= f.label :correct %>
    <%= link_to_remove_field "Remove", f %>
  </div>
</li>

app/views/backoffice/surveys/_question_fields.html.erb
<li>
  <div class="row">
    <div class="col-lg-4">
      <div class="form-group">
        <label for="">Name</label>
        <%= f.text_field :text, class: 'form-control' %>
      </div>
    </div>
    <div class="col-lg-6 field">
      <ul class="list-unstyled">
        <%= f.fields_for :options do |builder| %>
          <%= render "option_fields", :f => builder %>
        <% end %>
      </ul>
      <%= link_to_add_field "Add a new Option", f, :options %>
      <br/ >
      <%= link_to_remove_field "Remove Question", f %>
    </div>
  </div>
</li>

app/views/backoffice/surveys/edit.html.erb
<div class="container">
  <h2>Edit <%= @survey.name %> Survey</h2>
  <%= render 'form' %>
  </div>

app/views/backoffice/surveys/index.html.erb
<div class="container">
  <h3>My Surveys</h3>
  <%= link_to 'Create new Survey', new_backoffice_survey_path, class: 'btn btn-primary pull-right' %>
  <table class="table">
    <thead>
      <tr>
        <th>Created at</th>
        <th>Survey Name</th>
        <th>Responses</th>
        <th>Attempts Limit</th>
        <th>Status</th>
        <th></th>
      </tr>
    </thead>
    <tboddy>
      <% @surveys.each do |survey| %>
        <tr>
          <td><%= survey.created_at.strftime("%d/%m/%Y")  %></td>
          <td><%= survey.name %></td>
          <td><%= survey.attempts.size %></td>
          <td><%= survey.attempts_number %></td>
          <td><%= survey_status(survey) %></td>
          <td>
            <%= link_to 'Stats', backoffice_survey_path(survey), class: 'btn btn-primary btn-sm' %>
            <%= link_to 'Edit', edit_backoffice_survey_path(survey), class: 'btn btn-primary btn-sm' %>
          </td>
        </tr>
      <% end %>
    </tboddy>
  </table>
</div>

app/views/backoffice/surveys/new.html.erb
<h2>New Survey</h2>
<%= render 'form' %>

app/views/backoffice/surveys/show.html.erb
<h3><%= @survey.name %></h3>