config/routes.rb
SurveysApp::Application.routes.draw do

  namespace :backoffice do
    resources :surveys, except: [:show] do 
      resources :questions, only: [:new, :create, :edit, :update, :destroy]
    end
    resources :attempts, :only => [:new, :create]
  end

  resources :surveys, only: [:index] do 
    resources :attempts, :only => [:new, :create] do 
      member {get 'results'}
    end
  end

  resources :attempts, only: [:index] do 
    member { get 'results' }
  end

  devise_for :users
  get "home/index"

  root 'surveys#index'

end

app/views/layouts/_authenticated_nav.html.erb
<%= content_for :left_options do %>
  <li class="<%= 'active' if section?('surveys') %>">
    <%= link_to 'Available Surveys', surveys_path %>
  </li>
  <li class="<%= 'active' if section?('attempts') %>">
    <%= link_to 'My Results', attempts_path %>
  </li>
  <li class="<%= 'active' if section?('backoffice') %>">
    <%= link_to 'My Surveys', backoffice_surveys_path %>
  </li>
<% end %>
<%= content_for :right_options do %>
  <li >
    <%= link_to 'Logout', destroy_user_session_path, method: :delete %>
  </li>
<% end %>
<%= render template: 'layouts/nav_template' %>

app/views/layouts/_guest_nav.html.erb
<%= content_for :right_options do %>
  <li>
    <%= link_to 'Log in', new_user_session_path %>
  </li>
  <li>
    <%= link_to 'Sign up', new_user_registration_path %>
  </li>
<% end %>
<%= render template: 'layouts/nav_template' %>

app/views/layouts/_sidebar.html.erb
<div class="col-lg-4 l-full-height bottom-padding-buffer">
  <div class="well l-full-height l-overflow-y reset-bottom-margin">
    <%= yield %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>SurveysApp</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<header>
  <%= yield :header %>
</header>
<%= content_for?(:content) ? yield(:content) : yield %>  
<footer>
  <%= yield :footer %>
</footer>

</body>
</html>

app/views/layouts/authenticated.html.erb
<%= content_for :header do %>
  <%= render 'layouts/authenticated_nav' %>
<% end %>
<%= render template: 'layouts/application' %>

app/views/layouts/guest.html.erb
<%= content_for :header do %>
  <%= render 'layouts/guest_nav' %>
<% end %>
<%= render template: 'layouts/application' %>

app/views/layouts/nav_template.html.erb
<nav class="navbar-inverse navbar-fixed-top" role="navigation">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <%= link_to 'Surveys App', root_path, class: 'navbar-brand' %>
    </div>
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">         
        <%= yield (:left_options) %>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <%= yield(:right_options) %>
      </ul>
    </div>
  </div>
</nav>